### ISSUE TITLE
Android Support Latest Version of Cordova

### ISSUE THREAD

**Issue by johnnymajor** [Wizcorp/phonegap-plugin-wizViewManager#82]
Looks like Cordova has changed the Android cordovawebView. Errors with "evaluateJavascript", "post", "getSettings" etc.

Cordova 5.4

Some information I found - https://github.com/katzer/cordova-plugin-local-notifications/issues/535;

<img width="998" alt="screen shot 2015-12-30 at 3 37 33 pm" src="https://cloud.githubusercontent.com/assets/2379237/12057899/b0ba3040-af0b-11e5-94d6-93db1cd9231d.png">

Thanks

**Comment by jrouault** [comment]
Hello,
This issue should have been fixed with #81. However, it's on develop branch, not master.
Could you please check if using develop branch solves your issue? If so, I will have a look if we can make a new release.

**Comment by johnnymajor** [comment]
Develop branch does fix the issue! Thanks

**Comment by jrouault** [comment]
Thank you for your feedback! I will check if we can have a release in order to avoid this kind of situation for other users.
I'll post again here when that's done so that you know you no longer need to use develop branch.
